# Generated by Django 2.1.2 on 2018-10-14 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DespenseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Despensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despensor_uid', models.CharField(max_length=50)),
                ('medicine_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Low', 'LO'), ('HIGH', 'HI'), ('Medium', 'MI')], max_length=50)),
                ('composition_array', models.ManyToManyField(to='dbmanager.Composition')),
            ],
        ),
        migrations.CreateModel(
            name='PillSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('additional_notes', models.CharField(choices=[('AfterFood', 'af'), ('Empty Stomach', 'ES')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('composition', models.ManyToManyField(to='dbmanager.Composition')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanager.PrescriptionMedicine'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='schedules',
            field=models.ManyToManyField(to='dbmanager.PillSchedule'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despensor',
            name='medicine_list',
            field=models.ManyToManyField(to='dbmanager.PrescriptionMedicine'),
        ),
        migrations.AddField(
            model_name='despensor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despenselog',
            name='despensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanager.Despensor'),
        ),
    ]
