# Generated by Django 2.1.2 on 2018-10-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0002_auto_20181014_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillschedule',
            name='additional_notes',
        ),
        migrations.AddField(
            model_name='pillschedule',
            name='condition',
            field=models.CharField(choices=[('AF', 'After Food'), ('AT', 'Anytime'), ('ES', 'Empty Stomach')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='druginteraction',
            name='severity',
            field=models.CharField(choices=[('LO', 'Low'), ('HI', 'High'), ('MI', 'Medium')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='composition',
            field=models.ManyToManyField(blank=True, default=None, to='dbmanager.Composition'),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='drug_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
