# Generated by Django 2.1.2 on 2018-10-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0003_auto_20181014_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despensor',
            old_name='medicine_list',
            new_name='medicine_prescription_validation',
        ),
        migrations.RemoveField(
            model_name='despensor',
            name='medicine_count',
        ),
    ]
