# Generated by Django 2.1.2 on 2018-10-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0004_auto_20181014_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugDispensorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_count', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanager.PrescriptionMedicine')),
            ],
        ),
    ]
