# Generated by Django 2.1.2 on 2018-10-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0005_drugdispensorlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='despensor',
            name='drugs',
            field=models.ManyToManyField(to='dbmanager.DrugDispensorList'),
        ),
    ]
