# Generated by Django 2.1.2 on 2018-10-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0006_despensor_drugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despensor',
            name='drugs',
        ),
        migrations.AddField(
            model_name='drugdispensorlist',
            name='despensor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dbmanager.Despensor'),
            preserve_default=False,
        ),
    ]
