# Generated by Django 2.1.2 on 2018-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0007_auto_20181014_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despensor',
            name='despensor_uid',
            field=models.IntegerField(),
        ),
    ]
