# Generated by Django 2.1.2 on 2018-10-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0008_auto_20181014_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillschedule',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
